/*
 * [미사용 코드 - 주석 처리]
 * 이 파일은 USB HID 디스크립터 (NKRO 키보드, 코나미 조이스틱) 관련 코드로,
 * 현재 프로젝트(초음파 세척기/UV 살균기)에서 사용하지 않습니다.
 */

#if 0  // 미사용 코드 시작

#pragma once

#include "ACIO.h"

#define TUD_HID_REPORT_DESC_KEYBOARD_NKRO(...) \
  HID_USAGE_PAGE ( HID_USAGE_PAGE_DESKTOP),\
  HID_USAGE (HID_USAGE_DESKTOP_KEYBOARD),\
  HID_COLLECTION (HID_COLLECTION_APPLICATION),\
  /* Report ID if any */\
  __VA_ARGS__ \
  /* Keyboard Modifiers */ \
    HID_USAGE_PAGE(HID_USAGE_PAGE_KEYBOARD),\
      HID_USAGE_MIN(HID_KEY_CONTROL_LEFT),\
      HID_USAGE_MAX(HID_KEY_GUI_RIGHT),\
      HID_LOGICAL_MIN(0),\
      HID_LOGICAL_MAX(1),\
      HID_REPORT_SIZE(1),\
      HID_REPORT_COUNT(8),\
      HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE),\
      /* 104 Keyas as bitmap */ \
      HID_USAGE_MIN(0),\
      HID_USAGE_MAX(104 - 1),\
      HID_LOGICAL_MIN(0),\
      HID_LOGICAL_MAX(1),\
      HID_REPORT_SIZE(1),\
      HID_REPORT_COUNT(104),\
      HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE),\
  HID_COLLECTION_END

#define ACIO_HID_REPORT_DESC_KONAMI_JOYSTICK() \
	HID_USAGE_PAGE(HID_USAGE_PAGE_DESKTOP), \
	HID_USAGE(HID_USAGE_DESKTOP_JOYSTICK), \
	HID_COLLECTION(HID_COLLECTION_APPLICATION), \
		HID_USAGE(HID_USAGE_DESKTOP_POINTER), \
		HID_COLLECTION(HID_COLLECTION_PHYSICAL), \
			HID_USAGE_PAGE(HID_USAGE_PAGE_DESKTOP), \
			HID_USAGE(HID_USAGE_DESKTOP_X), \
			HID_USAGE(HID_USAGE_DESKTOP_Y), \
			HID_LOGICAL_MIN_N(-128, 2), \
			HID_LOGICAL_MAX(127), \
			HID_REPORT_SIZE(8), \
			HID_REPORT_COUNT(2), \
			HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE), \
			HID_USAGE_PAGE(HID_USAGE_PAGE_BUTTON), \
			HID_USAGE_MIN(0x01), \
			HID_USAGE_MAX(0x10), \
			HID_LOGICAL_MIN(0), \
			HID_LOGICAL_MAX(1), \
			HID_REPORT_SIZE(1), \
			HID_REPORT_COUNT(16), \
			HID_INPUT(HID_DATA | HID_VARIABLE | HID_ABSOLUTE), \
			HID_REPORT_SIZE(8), \
			HID_REPORT_COUNT(1), \
			HID_INPUT(HID_CONSTANT | HID_VARIABLE | HID_ABSOLUTE), \
		HID_COLLECTION_END, \
	HID_COLLECTION_END

#endif  // 미사용 코드 끝
