/*
 * [미사용 코드 - 주석 처리]
 * 이 파일은 USB 키보드 관련 코드로, 현재 프로젝트(초음파 세척기/UV 살균기)에서 사용하지 않습니다.
 */

#if 0  // 미사용 코드 시작

#pragma once

#include "ACIO.h"

typedef unsigned char Keyboard_Modifier;
typedef unsigned char Keyboard_ScanCode;
typedef struct {
	unsigned char byte_offset;
	unsigned char bitmask;
} NKRO_Key;

#define KEY_MOD_LCTRL			 ((Keyboard_Modifier) 0x01)
#define KEY_MOD_LSHIFT			 ((Keyboard_Modifier) 0x02)
#define KEY_MOD_LALT			 ((Keyboard_Modifier) 0x04)
#define KEY_MOD_LMETA			 ((Keyboard_Modifier) 0x08)
#define KEY_MOD_RCTRL			 ((Keyboard_Modifier) 0x10)
#define KEY_MOD_RSHIFT			 ((Keyboard_Modifier) 0x20)
#define KEY_MOD_RALT			 ((Keyboard_Modifier) 0x40)
#define KEY_MOD_RMETA			 ((Keyboard_Modifier) 0x80)

#define KEY_NONE				 ((Keyboard_ScanCode) 0x00)
#define KEY_ERR_OVF				 ((Keyboard_ScanCode) 0x01)
#define KEY_A		 			 ((Keyboard_ScanCode) 0x04)
#define KEY_B					 ((Keyboard_ScanCode) 0x05)
#define KEY_C					 ((Keyboard_ScanCode) 0x06)
#define KEY_D					 ((Keyboard_ScanCode) 0x07)
#define KEY_E					 ((Keyboard_ScanCode) 0x08)
#define KEY_F					 ((Keyboard_ScanCode) 0x09)
#define KEY_G					 ((Keyboard_ScanCode) 0x0a)
#define KEY_H					 ((Keyboard_ScanCode) 0x0b)
#define KEY_I					 ((Keyboard_ScanCode) 0x0c)
#define KEY_J					 ((Keyboard_ScanCode) 0x0d)
#define KEY_K					 ((Keyboard_ScanCode) 0x0e)
#define KEY_L					 ((Keyboard_ScanCode) 0x0f)
#define KEY_M					 ((Keyboard_ScanCode) 0x10)
#define KEY_N					 ((Keyboard_ScanCode) 0x11)
#define KEY_O					 ((Keyboard_ScanCode) 0x12)
#define KEY_P					 ((Keyboard_ScanCode) 0x13)
#define KEY_Q					 ((Keyboard_ScanCode) 0x14)
#define KEY_R					 ((Keyboard_ScanCode) 0x15)
#define KEY_S					 ((Keyboard_ScanCode) 0x16)
#define KEY_T					 ((Keyboard_ScanCode) 0x17)
#define KEY_U					 ((Keyboard_ScanCode) 0x18)
#define KEY_V					 ((Keyboard_ScanCode) 0x19)
#define KEY_W					 ((Keyboard_ScanCode) 0x1a)
#define KEY_X					 ((Keyboard_ScanCode) 0x1b)
#define KEY_Y					 ((Keyboard_ScanCode) 0x1c)
#define KEY_Z					 ((Keyboard_ScanCode) 0x1d)
#define KEY_1					 ((Keyboard_ScanCode) 0x1e)
#define KEY_2					 ((Keyboard_ScanCode) 0x1f)
#define KEY_3					 ((Keyboard_ScanCode) 0x20)
#define KEY_4					 ((Keyboard_ScanCode) 0x21)
#define KEY_5					 ((Keyboard_ScanCode) 0x22)
#define KEY_6					 ((Keyboard_ScanCode) 0x23)
#define KEY_7					 ((Keyboard_ScanCode) 0x24)
#define KEY_8					 ((Keyboard_ScanCode) 0x25)
#define KEY_9					 ((Keyboard_ScanCode) 0x26)
#define KEY_0					 ((Keyboard_ScanCode) 0x27)
#define KEY_ENTER				 ((Keyboard_ScanCode) 0x28)
#define KEY_ESC					 ((Keyboard_ScanCode) 0x29)
#define KEY_BACKSPACE			 ((Keyboard_ScanCode) 0x2a)
#define KEY_TAB					 ((Keyboard_ScanCode) 0x2b)
#define KEY_SPACE				 ((Keyboard_ScanCode) 0x2c)
#define KEY_MINUS				 ((Keyboard_ScanCode) 0x2d)
#define KEY_EQUAL				 ((Keyboard_ScanCode) 0x2e)
#define KEY_LEFTBRACE			 ((Keyboard_ScanCode) 0x2f)
#define KEY_RIGHTBRACE			 ((Keyboard_ScanCode) 0x30)
#define KEY_BACKSLASH			 ((Keyboard_ScanCode) 0x31)
#define KEY_HASHTILDE			 ((Keyboard_ScanCode) 0x32)
#define KEY_SEMICOLON			 ((Keyboard_ScanCode) 0x33)
#define KEY_APOSTROPHE			 ((Keyboard_ScanCode) 0x34)
#define KEY_GRAVE				 ((Keyboard_ScanCode) 0x35)
#define KEY_COMMA				 ((Keyboard_ScanCode) 0x36)
#define KEY_DOT					 ((Keyboard_ScanCode) 0x37)
#define KEY_SLASH				 ((Keyboard_ScanCode) 0x38)
#define KEY_CAPSLOCK			 ((Keyboard_ScanCode) 0x39)
#define KEY_F1					 ((Keyboard_ScanCode) 0x3a)
#define KEY_F2					 ((Keyboard_ScanCode) 0x3b)
#define KEY_F3					 ((Keyboard_ScanCode) 0x3c)
#define KEY_F4					 ((Keyboard_ScanCode) 0x3d)
#define KEY_F5					 ((Keyboard_ScanCode) 0x3e)
#define KEY_F6					 ((Keyboard_ScanCode) 0x3f)
#define KEY_F7					 ((Keyboard_ScanCode) 0x40)
#define KEY_F8					 ((Keyboard_ScanCode) 0x41)
#define KEY_F9					 ((Keyboard_ScanCode) 0x42)
#define KEY_F10					 ((Keyboard_ScanCode) 0x43)
#define KEY_F11					 ((Keyboard_ScanCode) 0x44)
#define KEY_F12					 ((Keyboard_ScanCode) 0x45)
#define KEY_SYSRQ				 ((Keyboard_ScanCode) 0x46)
#define KEY_SCROLLLOCK			 ((Keyboard_ScanCode) 0x47)
#define KEY_PAUSE				 ((Keyboard_ScanCode) 0x48)
#define KEY_INSERT				 ((Keyboard_ScanCode) 0x49)
#define KEY_HOME				 ((Keyboard_ScanCode) 0x4a)
#define KEY_PAGEUP				 ((Keyboard_ScanCode) 0x4b)
#define KEY_DELETE				 ((Keyboard_ScanCode) 0x4c)
#define KEY_END					 ((Keyboard_ScanCode) 0x4d)
#define KEY_PAGEDOWN			 ((Keyboard_ScanCode) 0x4e)
#define KEY_RIGHT				 ((Keyboard_ScanCode) 0x4f)
#define KEY_LEFT				 ((Keyboard_ScanCode) 0x50)
#define KEY_DOWN				 ((Keyboard_ScanCode) 0x51)
#define KEY_UP					 ((Keyboard_ScanCode) 0x52)
#define KEY_NUMLOCK				 ((Keyboard_ScanCode) 0x53)
#define KEY_KPSLASH				 ((Keyboard_ScanCode) 0x54)
#define KEY_KPASTERISK			 ((Keyboard_ScanCode) 0x55)
#define KEY_KPMINUS				 ((Keyboard_ScanCode) 0x56)
#define KEY_KPPLUS				 ((Keyboard_ScanCode) 0x57)
#define KEY_KPENTER				 ((Keyboard_ScanCode) 0x58)
#define KEY_KP1					 ((Keyboard_ScanCode) 0x59)
#define KEY_KP2					 ((Keyboard_ScanCode) 0x5a)
#define KEY_KP3					 ((Keyboard_ScanCode) 0x5b)
#define KEY_KP4					 ((Keyboard_ScanCode) 0x5c)
#define KEY_KP5					 ((Keyboard_ScanCode) 0x5d)
#define KEY_KP6					 ((Keyboard_ScanCode) 0x5e)
#define KEY_KP7					 ((Keyboard_ScanCode) 0x5f)
#define KEY_KP8					 ((Keyboard_ScanCode) 0x60)
#define KEY_KP9					 ((Keyboard_ScanCode) 0x61)
#define KEY_KP0					 ((Keyboard_ScanCode) 0x62)
#define KEY_KPDOT				 ((Keyboard_ScanCode) 0x63)
#define KEY_102ND				 ((Keyboard_ScanCode) 0x64)
#define KEY_COMPOSE				 ((Keyboard_ScanCode) 0x65)
#define KEY_POWER				 ((Keyboard_ScanCode) 0x66)
#define KEY_KPEQUAL				 ((Keyboard_ScanCode) 0x67)
#define KEY_F13					 ((Keyboard_ScanCode) 0x68)
#define KEY_F14					 ((Keyboard_ScanCode) 0x69)
#define KEY_F15					 ((Keyboard_ScanCode) 0x6a)
#define KEY_F16					 ((Keyboard_ScanCode) 0x6b)
#define KEY_F17					 ((Keyboard_ScanCode) 0x6c)
#define KEY_F18					 ((Keyboard_ScanCode) 0x6d)
#define KEY_F19					 ((Keyboard_ScanCode) 0x6e)
#define KEY_F20					 ((Keyboard_ScanCode) 0x6f)
#define KEY_F21					 ((Keyboard_ScanCode) 0x70)
#define KEY_F22					 ((Keyboard_ScanCode) 0x71)
#define KEY_F23					 ((Keyboard_ScanCode) 0x72)
#define KEY_F24					 ((Keyboard_ScanCode) 0x73)
#define KEY_OPEN				 ((Keyboard_ScanCode) 0x74)
#define KEY_HELP				 ((Keyboard_ScanCode) 0x75)
#define KEY_PROPS				 ((Keyboard_ScanCode) 0x76)
#define KEY_FRONT				 ((Keyboard_ScanCode) 0x77)
#define KEY_STOP				 ((Keyboard_ScanCode) 0x78)
#define KEY_AGAIN				 ((Keyboard_ScanCode) 0x79)
#define KEY_UNDO				 ((Keyboard_ScanCode) 0x7a)
#define KEY_CUT					 ((Keyboard_ScanCode) 0x7b)
#define KEY_COPY				 ((Keyboard_ScanCode) 0x7c)
#define KEY_PASTE				 ((Keyboard_ScanCode) 0x7d)
#define KEY_FIND				 ((Keyboard_ScanCode) 0x7e)
#define KEY_MUTE				 ((Keyboard_ScanCode) 0x7f)
#define KEY_VOLUMEUP			 ((Keyboard_ScanCode) 0x80)
#define KEY_VOLUMEDOWN			 ((Keyboard_ScanCode) 0x81)
#define KEY_KPCOMMA				 ((Keyboard_ScanCode) 0x85)
#define KEY_RO					 ((Keyboard_ScanCode) 0x87)
#define KEY_KATAKANAHIRAGANA	 ((Keyboard_ScanCode) 0x88)
#define KEY_YEN					 ((Keyboard_ScanCode) 0x89)
#define KEY_HENKAN				 ((Keyboard_ScanCode) 0x8a)
#define KEY_MUHENKAN			 ((Keyboard_ScanCode) 0x8b)
#define KEY_KPJPCOMMA			 ((Keyboard_ScanCode) 0x8c)
#define KEY_HANGEUL				 ((Keyboard_ScanCode) 0x90)
#define KEY_HANJA				 ((Keyboard_ScanCode) 0x91)
#define KEY_KATAKANA			 ((Keyboard_ScanCode) 0x92)
#define KEY_HIRAGANA			 ((Keyboard_ScanCode) 0x93)
#define KEY_ZENKAKUHANKAKU		 ((Keyboard_ScanCode) 0x94)
#define KEY_KPLEFTPAREN			 ((Keyboard_ScanCode) 0xb6)
#define KEY_KPRIGHTPAREN		 ((Keyboard_ScanCode) 0xb7)
#define KEY_LEFTCTRL			 ((Keyboard_ScanCode) 0xe0)
#define KEY_LEFTSHIFT			 ((Keyboard_ScanCode) 0xe1)
#define KEY_LEFTALT				 ((Keyboard_ScanCode) 0xe2)
#define KEY_LEFTMETA			 ((Keyboard_ScanCode) 0xe3)
#define KEY_RIGHTCTRL			 ((Keyboard_ScanCode) 0xe4)
#define KEY_RIGHTSHIFT			 ((Keyboard_ScanCode) 0xe5)
#define KEY_RIGHTALT			 ((Keyboard_ScanCode) 0xe6)
#define KEY_RIGHTMETA			 ((Keyboard_ScanCode) 0xe7)
#define KEY_MEDIA_PLAYPAUSE		 ((Keyboard_ScanCode) 0xe8)
#define KEY_MEDIA_STOPCD		 ((Keyboard_ScanCode) 0xe9)
#define KEY_MEDIA_PREVIOUSSONG	 ((Keyboard_ScanCode) 0xea)
#define KEY_MEDIA_NEXTSONG		 ((Keyboard_ScanCode) 0xeb)
#define KEY_MEDIA_EJECTCD		 ((Keyboard_ScanCode) 0xec)
#define KEY_MEDIA_VOLUMEUP		 ((Keyboard_ScanCode) 0xed)
#define KEY_MEDIA_VOLUMEDOWN	 ((Keyboard_ScanCode) 0xee)
#define KEY_MEDIA_MUTE			 ((Keyboard_ScanCode) 0xef)
#define KEY_MEDIA_WWW			 ((Keyboard_ScanCode) 0xf0)
#define KEY_MEDIA_BACK			 ((Keyboard_ScanCode) 0xf1)
#define KEY_MEDIA_FORWARD		 ((Keyboard_ScanCode) 0xf2)
#define KEY_MEDIA_STOP			 ((Keyboard_ScanCode) 0xf3)
#define KEY_MEDIA_FIND			 ((Keyboard_ScanCode) 0xf4)
#define KEY_MEDIA_SCROLLUP		 ((Keyboard_ScanCode) 0xf5)
#define KEY_MEDIA_SCROLLDOWN	 ((Keyboard_ScanCode) 0xf6)
#define KEY_MEDIA_EDIT			 ((Keyboard_ScanCode) 0xf7)
#define KEY_MEDIA_SLEEP			 ((Keyboard_ScanCode) 0xf8)
#define KEY_MEDIA_COFFEE		 ((Keyboard_ScanCode) 0xf9)
#define KEY_MEDIA_REFRESH		 ((Keyboard_ScanCode) 0xfa)
#define KEY_MEDIA_CALC			 ((Keyboard_ScanCode) 0xfb)

#define NKRO_NONE				((NKRO_Key) {KEY_NONE		>> 3, (0x01 << (KEY_NONE		 & 0x07)) })
#define NKRO_ERR_OVF			((NKRO_Key) {KEY_ERR_OVF	>> 3, (0x01 << (KEY_ERR_OVF		 & 0x07)) })
#define NKRO_A		 			((NKRO_Key) {KEY_A		 	>> 3, (0x01 << (KEY_A		 	 & 0x07)) })
#define NKRO_B					((NKRO_Key) {KEY_B			>> 3, (0x01 << (KEY_B			 & 0x07)) })
#define NKRO_C					((NKRO_Key) {KEY_C			>> 3, (0x01 << (KEY_C			 & 0x07)) })
#define NKRO_D					((NKRO_Key) {KEY_D			>> 3, (0x01 << (KEY_D			 & 0x07)) })
#define NKRO_E					((NKRO_Key) {KEY_E			>> 3, (0x01 << (KEY_E			 & 0x07)) })
#define NKRO_F					((NKRO_Key) {KEY_F			>> 3, (0x01 << (KEY_F			 & 0x07)) })
#define NKRO_G					((NKRO_Key) {KEY_G			>> 3, (0x01 << (KEY_G			 & 0x07)) })
#define NKRO_H					((NKRO_Key) {KEY_H			>> 3, (0x01 << (KEY_H			 & 0x07)) })
#define NKRO_I					((NKRO_Key) {KEY_I			>> 3, (0x01 << (KEY_I			 & 0x07)) })
#define NKRO_J					((NKRO_Key) {KEY_J			>> 3, (0x01 << (KEY_J			 & 0x07)) })
#define NKRO_K					((NKRO_Key) {KEY_K			>> 3, (0x01 << (KEY_K			 & 0x07)) })
#define NKRO_L					((NKRO_Key) {KEY_L			>> 3, (0x01 << (KEY_L			 & 0x07)) })
#define NKRO_M					((NKRO_Key) {KEY_M			>> 3, (0x01 << (KEY_M			 & 0x07)) })
#define NKRO_N					((NKRO_Key) {KEY_N			>> 3, (0x01 << (KEY_N			 & 0x07)) })
#define NKRO_O					((NKRO_Key) {KEY_O			>> 3, (0x01 << (KEY_O			 & 0x07)) })
#define NKRO_P					((NKRO_Key) {KEY_P			>> 3, (0x01 << (KEY_P			 & 0x07)) })
#define NKRO_Q					((NKRO_Key) {KEY_Q			>> 3, (0x01 << (KEY_Q			 & 0x07)) })
#define NKRO_R					((NKRO_Key) {KEY_R			>> 3, (0x01 << (KEY_R			 & 0x07)) })
#define NKRO_S					((NKRO_Key) {KEY_S			>> 3, (0x01 << (KEY_S			 & 0x07)) })
#define NKRO_T					((NKRO_Key) {KEY_T			>> 3, (0x01 << (KEY_T			 & 0x07)) })
#define NKRO_U					((NKRO_Key) {KEY_U			>> 3, (0x01 << (KEY_U			 & 0x07)) })
#define NKRO_V					((NKRO_Key) {KEY_V			>> 3, (0x01 << (KEY_V			 & 0x07)) })
#define NKRO_W					((NKRO_Key) {KEY_W			>> 3, (0x01 << (KEY_W			 & 0x07)) })
#define NKRO_X					((NKRO_Key) {KEY_X			>> 3, (0x01 << (KEY_X			 & 0x07)) })
#define NKRO_Y					((NKRO_Key) {KEY_Y			>> 3, (0x01 << (KEY_Y			 & 0x07)) })
#define NKRO_Z					((NKRO_Key) {KEY_Z			>> 3, (0x01 << (KEY_Z			 & 0x07)) })
#define NKRO_1					((NKRO_Key) {KEY_1			>> 3, (0x01 << (KEY_1			 & 0x07)) })
#define NKRO_2					((NKRO_Key) {KEY_2			>> 3, (0x01 << (KEY_2			 & 0x07)) })
#define NKRO_3					((NKRO_Key) {KEY_3			>> 3, (0x01 << (KEY_3			 & 0x07)) })
#define NKRO_4					((NKRO_Key) {KEY_4			>> 3, (0x01 << (KEY_4			 & 0x07)) })
#define NKRO_5					((NKRO_Key) {KEY_5			>> 3, (0x01 << (KEY_5			 & 0x07)) })
#define NKRO_6					((NKRO_Key) {KEY_6			>> 3, (0x01 << (KEY_6			 & 0x07)) })
#define NKRO_7					((NKRO_Key) {KEY_7			>> 3, (0x01 << (KEY_7			 & 0x07)) })
#define NKRO_8					((NKRO_Key) {KEY_8			>> 3, (0x01 << (KEY_8			 & 0x07)) })
#define NKRO_9					((NKRO_Key) {KEY_9			>> 3, (0x01 << (KEY_9			 & 0x07)) })
#define NKRO_0					((NKRO_Key) {KEY_0			>> 3, (0x01 << (KEY_0			 & 0x07)) })
#define NKRO_ENTER				((NKRO_Key) {KEY_ENTER		>> 3, (0x01 << (KEY_ENTER		 & 0x07)) })
#define NKRO_ESC				((NKRO_Key) {KEY_ESC		>> 3, (0x01 << (KEY_ESC			 & 0x07)) })
#define NKRO_BACKSPACE			((NKRO_Key) {KEY_BACKSPACE	>> 3, (0x01 << (KEY_BACKSPACE	 & 0x07)) })
#define NKRO_TAB				((NKRO_Key) {KEY_TAB		>> 3, (0x01 << (KEY_TAB			 & 0x07)) })
#define NKRO_SPACE				((NKRO_Key) {KEY_SPACE		>> 3, (0x01 << (KEY_SPACE		 & 0x07)) })
#define NKRO_MINUS				((NKRO_Key) {KEY_MINUS		>> 3, (0x01 << (KEY_MINUS		 & 0x07)) })
#define NKRO_EQUAL				((NKRO_Key) {KEY_EQUAL		>> 3, (0x01 << (KEY_EQUAL		 & 0x07)) })
#define NKRO_LEFTBRACE			((NKRO_Key) {KEY_LEFTBRACE	>> 3, (0x01 << (KEY_LEFTBRACE	 & 0x07)) })
#define NKRO_RIGHTBRACE			((NKRO_Key) {KEY_RIGHTBRACE	>> 3, (0x01 << (KEY_RIGHTBRACE	 & 0x07)) })
#define NKRO_BACKSLASH			((NKRO_Key) {KEY_BACKSLASH	>> 3, (0x01 << (KEY_BACKSLASH	 & 0x07)) })
#define NKRO_HASHTILDE			((NKRO_Key) {KEY_HASHTILDE	>> 3, (0x01 << (KEY_HASHTILDE	 & 0x07)) })
#define NKRO_SEMICOLON			((NKRO_Key) {KEY_SEMICOLON	>> 3, (0x01 << (KEY_SEMICOLON	 & 0x07)) })
#define NKRO_APOSTROPHE			((NKRO_Key) {KEY_APOSTROPHE	>> 3, (0x01 << (KEY_APOSTROPHE	 & 0x07)) })
#define NKRO_GRAVE				((NKRO_Key) {KEY_GRAVE		>> 3, (0x01 << (KEY_GRAVE		 & 0x07)) })
#define NKRO_COMMA				((NKRO_Key) {KEY_COMMA		>> 3, (0x01 << (KEY_COMMA		 & 0x07)) })
#define NKRO_DOT				((NKRO_Key) {KEY_DOT		>> 3, (0x01 << (KEY_DOT			 & 0x07)) })
#define NKRO_SLASH				((NKRO_Key) {KEY_SLASH		>> 3, (0x01 << (KEY_SLASH		 & 0x07)) })
#define NKRO_CAPSLOCK			((NKRO_Key) {KEY_CAPSLOCK	>> 3, (0x01 << (KEY_CAPSLOCK	 & 0x07)) })
#define NKRO_F1					((NKRO_Key) {KEY_F1			>> 3, (0x01 << (KEY_F1			 & 0x07)) })
#define NKRO_F2					((NKRO_Key) {KEY_F2			>> 3, (0x01 << (KEY_F2			 & 0x07)) })
#define NKRO_F3					((NKRO_Key) {KEY_F3			>> 3, (0x01 << (KEY_F3			 & 0x07)) })
#define NKRO_F4					((NKRO_Key) {KEY_F4			>> 3, (0x01 << (KEY_F4			 & 0x07)) })
#define NKRO_F5					((NKRO_Key) {KEY_F5			>> 3, (0x01 << (KEY_F5			 & 0x07)) })
#define NKRO_F6					((NKRO_Key) {KEY_F6			>> 3, (0x01 << (KEY_F6			 & 0x07)) })
#define NKRO_F7					((NKRO_Key) {KEY_F7			>> 3, (0x01 << (KEY_F7			 & 0x07)) })
#define NKRO_F8					((NKRO_Key) {KEY_F8			>> 3, (0x01 << (KEY_F8			 & 0x07)) })
#define NKRO_F9					((NKRO_Key) {KEY_F9			>> 3, (0x01 << (KEY_F9			 & 0x07)) })
#define NKRO_F10				((NKRO_Key) {KEY_F10		>> 3, (0x01 << (KEY_F10			 & 0x07)) })
#define NKRO_F11				((NKRO_Key) {KEY_F11		>> 3, (0x01 << (KEY_F11			 & 0x07)) })
#define NKRO_F12				((NKRO_Key) {KEY_F12		>> 3, (0x01 << (KEY_F12			 & 0x07)) })
#define NKRO_SYSRQ				((NKRO_Key) {KEY_SYSRQ		>> 3, (0x01 << (KEY_SYSRQ		 & 0x07)) })
#define NKRO_SCROLLLOCK			((NKRO_Key) {KEY_SCROLLLOCK	>> 3, (0x01 << (KEY_SCROLLLOCK	 & 0x07)) })
#define NKRO_PAUSE				((NKRO_Key) {KEY_PAUSE		>> 3, (0x01 << (KEY_PAUSE		 & 0x07)) })
#define NKRO_INSERT				((NKRO_Key) {KEY_INSERT		>> 3, (0x01 << (KEY_INSERT		 & 0x07)) })
#define NKRO_HOME				((NKRO_Key) {KEY_HOME		>> 3, (0x01 << (KEY_HOME		 & 0x07)) })
#define NKRO_PAGEUP				((NKRO_Key) {KEY_PAGEUP		>> 3, (0x01 << (KEY_PAGEUP		 & 0x07)) })
#define NKRO_DELETE				((NKRO_Key) {KEY_DELETE		>> 3, (0x01 << (KEY_DELETE		 & 0x07)) })
#define NKRO_END				((NKRO_Key) {KEY_END		>> 3, (0x01 << (KEY_END			 & 0x07)) })
#define NKRO_PAGEDOWN			((NKRO_Key) {KEY_PAGEDOWN	>> 3, (0x01 << (KEY_PAGEDOWN	 & 0x07)) })
#define NKRO_RIGHT				((NKRO_Key) {KEY_RIGHT		>> 3, (0x01 << (KEY_RIGHT		 & 0x07)) })
#define NKRO_LEFT				((NKRO_Key) {KEY_LEFT		>> 3, (0x01 << (KEY_LEFT		 & 0x07)) })
#define NKRO_DOWN				((NKRO_Key) {KEY_DOWN		>> 3, (0x01 << (KEY_DOWN		 & 0x07)) })
#define NKRO_UP					((NKRO_Key) {KEY_UP			>> 3, (0x01 << (KEY_UP			 & 0x07)) })
#define NKRO_NUMLOCK			((NKRO_Key) {KEY_NUMLOCK	>> 3, (0x01 << (KEY_NUMLOCK		 & 0x07)) })
#define NKRO_KPSLASH			((NKRO_Key) {KEY_KPSLASH	>> 3, (0x01 << (KEY_KPSLASH		 & 0x07)) })
#define NKRO_KPASTERISK			((NKRO_Key) {KEY_KPASTERISK	>> 3, (0x01 << (KEY_KPASTERISK	 & 0x07)) })
#define NKRO_KPMINUS			((NKRO_Key) {KEY_KPMINUS	>> 3, (0x01 << (KEY_KPMINUS		 & 0x07)) })
#define NKRO_KPPLUS				((NKRO_Key) {KEY_KPPLUS		>> 3, (0x01 << (KEY_KPPLUS		 & 0x07)) })
#define NKRO_KPENTER			((NKRO_Key) {KEY_KPENTER	>> 3, (0x01 << (KEY_KPENTER		 & 0x07)) })
#define NKRO_KP1				((NKRO_Key) {KEY_KP1		>> 3, (0x01 << (KEY_KP1			 & 0x07)) })
#define NKRO_KP2				((NKRO_Key) {KEY_KP2		>> 3, (0x01 << (KEY_KP2			 & 0x07)) })
#define NKRO_KP3				((NKRO_Key) {KEY_KP3		>> 3, (0x01 << (KEY_KP3			 & 0x07)) })
#define NKRO_KP4				((NKRO_Key) {KEY_KP4		>> 3, (0x01 << (KEY_KP4			 & 0x07)) })
#define NKRO_KP5				((NKRO_Key) {KEY_KP5		>> 3, (0x01 << (KEY_KP5			 & 0x07)) })
#define NKRO_KP6				((NKRO_Key) {KEY_KP6		>> 3, (0x01 << (KEY_KP6			 & 0x07)) })
#define NKRO_KP7				((NKRO_Key) {KEY_KP7		>> 3, (0x01 << (KEY_KP7			 & 0x07)) })
#define NKRO_KP8				((NKRO_Key) {KEY_KP8		>> 3, (0x01 << (KEY_KP8			 & 0x07)) })
#define NKRO_KP9				((NKRO_Key) {KEY_KP9		>> 3, (0x01 << (KEY_KP9			 & 0x07)) })
#define NKRO_KP0				((NKRO_Key) {KEY_KP0		>> 3, (0x01 << (KEY_KP0			 & 0x07)) })
#define NKRO_KPDOT				((NKRO_Key) {KEY_KPDOT		>> 3, (0x01 << (KEY_KPDOT		 & 0x07)) })
#define NKRO_102ND				((NKRO_Key) {KEY_102ND		>> 3, (0x01 << (KEY_102ND		 & 0x07)) })
#define NKRO_COMPOSE			((NKRO_Key) {KEY_COMPOSE	>> 3, (0x01 << (KEY_COMPOSE		 & 0x07)) })
#define NKRO_POWER				((NKRO_Key) {KEY_POWER		>> 3, (0x01 << (KEY_POWER		 & 0x07)) })
#define NKRO_KPEQUAL			((NKRO_Key) {KEY_KPEQUAL	>> 3, (0x01 << (KEY_KPEQUAL		 & 0x07)) })

#endif  // 미사용 코드 끝
