#pragma once

#include "ACIO.h"

typedef enum {
    ACIO_LOW,
    ACIO_HIGH,
    ACIO_INIT,
    ACIO_RISING,
    ACIO_RISING_DEBOUNCE,
    ACIO_FALLING,
    ACIO_FALLING_DEBOUNCE,
    ACIO_IDLE,
    ACIO_WAIT_FOR_RELEASE,
    ACIO_WAIT_FOR_AFTER_RELEASE,
    ACIO_WAIT_FOR_PRESS,
    ACIO_AFTER_RISING_DEBOUNCE,
    ACIO_N_MAX_RISING_DEBOUNCE
} ACIO_State;