#pragma once

#include "main.h"

#define USC_COST (5 * 60 * 1000)

void Read_Inputs();

typedef enum {
	TASK_CHARGER_INIT,
	TASK_CHARGER_IDLE_ENTRY,
	TASK_CHARGER_IDLE,
	TASK_CHARGER_CHARGING_ENTRY,
	TASK_CHARGER_CHARGING,
	TASK_CHARGER_STANDBY_ENTRY,
	TASK_CHARGER_STANDBY
} TASK_STATE_CHARGER;

void Task_Charger();


typedef enum {
	TASK_CLEANER_INIT,
	TASK_CLEANER_IDLE,
	TASK_CLEANER_CLEAN_ENTRY,
	TASK_CLEANER_CLEAN_UV,
	TASK_CLEANER_CLEAN_USC_FREQ_SCAN,
	TASK_CLEANER_CLEAN_USC,
	TASK_CLEANER_CLEAN_DONE,
	TASK_CLEANER_BATT_CHECK
} TASK_STATE_CLEANER;

void Task_Cleaner();


typedef enum {
	TASK_POWER_INIT,
	TASK_POWER_WFIDLE,
	TASK_POWER_STANDBY
} TASK_STATE_POWER;

void Task_Power();

typedef enum {
	TASK_FREQ_CHANGER_INIT,
	TASK_FREQ_CHANGER_RISING,
	TASK_FREQ_CHANGER_FALLING
} TASK_STATE_FREQ_CHANGER;

void Task_Freq_Changer();
